Console.Writeline ("Aham, aham-aham, aham-aham, ayy");
Console.Writeline ("Aham, aham-aham, aham-aham, ayy");
Console.Writeline ("Pau no cu da concorrência, aqui é o bife, porra");
Console.Writeline ("Ta-ra-ta-ta, ta-ra-ta-ta");

Console.Writeline ("Drip veneno, desce mais uma" foreground color = ConsoleColor.Red);
Console.Writeline ("Que hoje o rolê é bife e yung lixo" foreground color = ConsoleColor.Red);
Console.Writeline ("Só get over here que isso te ajuda" foreground color = ConsoleColor.Red);
Console.Writeline ("A ver a cena do trap caindo" foreground color = ConsoleColor.Red);
Console.Writeline ("Drip veneno, desce mais um" foreground color = ConsoleColor.Red);
Console.Writeline ("Que hoje o rolê é bife e yung lixo" foreground color = ConsoleColor.Red);
Console.Writeline ("Só get over here que isso te ajuda" foreground color = ConsoleColor.Red);
Console.Writeline ("A ver a cena do trap caindo" foreground color = ConsoleColor.Red);

Console.Writeline ("Tô correndo aqui nas ruas da grande Acari");
Console.Writeline ("Com um fusca rebaixado no estilo Bumblebee");
Console.Writeline ("Tem uns cara atrás de mim tentando me impedir");
Console.Writeline ("Quando eu entro na viela, eles não vêem pr'onde eu fugi");
Console.Writeline ("Eles têm alcance, mano, porque eu sou o bicho");
Console.Writeline ("Tu é Zeca Urubu, amigo, então 'cê fecha o bico");
Console.Writeline ("Eu pego criminoso, apareci no Datena");
Console.Writeline ("Com 100 mil no bolso, huh, Porsche Panamera");
Console.Writeline ("Ninguém me aguenta, velocidade da luz");
Console.Writeline ("Jogam até água benta, os cara já pegam a cruz");
Console.Writeline ("Na curva, pneu cantando, mano, e tu me mamando");
Console.Writeline ("Que nem Tá Dando Onda, eu sou o Cadu e tu é o Frango");
Console.Writeline ("Nível da potência, não tem como se igualar");
Console.Writeline ("Tamo' no pique mais alto que o próprio lobo-guará");
Console.Writeline ("Na hora de fazer rima, mano, eu sou tenebroso");
Console.Writeline ("Mando speed flow brabo, tipo XLR8");

Console.Writeline ("Drip veneno, desce mais uma" foreground color = ConsoleColor.Red);
Console.Writeline ("Que hoje o rolê é bife e yung lixo" foreground color = ConsoleColor.Red);
Console.Writeline ("Só get over here que isso te ajuda" foreground color = ConsoleColor.Red);
Console.Writeline ("A ver a cena do trap caindo" foreground color = ConsoleColor.Red);
Console.Writeline ("Drip veneno, desce mais um" foreground color = ConsoleColor.Red);
Console.Writeline ("Que hoje o rolê é bife e yung lixo" foreground color = ConsoleColor.Red);
Console.Writeline ("Só get over here que isso te ajuda" foreground color = ConsoleColor.Red);
Console.Writeline ("A ver a cena do trap caindo" foreground color = ConsoleColor.Red);

Console.Writeline("'Cê tá mal, 'cê tá slow, huh, tipo Hello Kitty");
Console.Writeline("No Angry Birds tá fudido, mano, tô no estilingue");
Console.Writeline("A Glock no automático, calibre 15");
Console.Writeline("Lanchando quatro embrasado, mano, eu já tô no pique, huh");
Console.Writeline("Fica tranquilo que nós não é meme");
Console.Writeline("Nós não perde a graça, huh, nós dura pra sempre");
Console.Writeline("Tu pensa que é fácil fazer isso e, mano, é mais ainda");
Console.Writeline("Quando tu lançar um hit, mano, eu já lancei é 30");
Console.Writeline("Nós tá tipo Johnny Test, cabeça pegando fogo");
Console.Writeline("Na raba das piriguete, speed no trap, as bitch estremece");
Console.Writeline("Os cara pensa que tem o flow, eu tô muito flex");
Console.Writeline("Eles tão correndo slow enquanto eu tenho swag");

Console.Writeline("Drip veneno, desce mais uma" foreground color = ConsoleColor.Red);
Console.Writeline("Que hoje o rolê é bife e yung lixo" foreground color = ConsoleColor.Red);
Console.Writeline("Só get over here que isso te ajuda" foreground color = ConsoleColor.Red);
Console.Writeline("A ver a cena do trap caindo" foreground color = ConsoleColor.Red);
Console.Writeline("Drip veneno, desce mais um" foreground color = ConsoleColor.Red);
Console.Writeline("Que hoje o rolê é bife e yung lixo" foreground color = ConsoleColor.Red);
Console.Writeline("Só get over here que isso te ajuda" foreground color = ConsoleColor.Red);
Console.Writeline("A ver a cena do trap caindo" foreground color = ConsoleColor.Red);